"""Pins the runtime the installer downloads: the exact PyPI wheels for the PySide6 and Pillow versions installed here,
each with its URL and SHA-256, written to installer/runtime.inc for GrammarSweeper.iss to include.

Run from the project root after changing the PySide6 version: python installer/pin_runtime.py. The installer refuses a
download whose hash does not match, so a changed or tampered file is never unpacked."""

from __future__ import annotations

import json
import sys
import urllib.request
from importlib.metadata import version
from pathlib import Path

OUT = Path(__file__).resolve().parent / "runtime.inc"
PACKAGES = (("PySide6_Essentials", "PYSIDE"), ("shiboken6", "SHIBOKEN"), ("Pillow", "PILLOW"))
PYTHON_TAG = f"cp{sys.version_info.major}{sys.version_info.minor}"


def wheel(package: str, release: str) -> dict:
    """The Windows 64-bit wheel for `release`, as PyPI describes it."""
    with urllib.request.urlopen(f"https://pypi.org/pypi/{package}/{release}/json", timeout=30) as reply:
        files = json.load(reply)["urls"]
    matches = [f for f in files if f["packagetype"] == "bdist_wheel" and f["filename"].endswith("win_amd64.whl")]
    if len(matches) > 1:  # a wheel per Python version (Pillow): take the one for the Python the exe bundles
        matches = [f for f in matches if f"-{PYTHON_TAG}-{PYTHON_TAG}-win_amd64" in f["filename"]]
    if len(matches) != 1:
        raise SystemExit(f"{package} {release}: expected one win_amd64 wheel on PyPI, found {len(matches)}")
    return matches[0]


def main() -> None:
    release = version("PySide6_Essentials")
    lines = [f"; Generated by installer/pin_runtime.py for PySide6 {release}. Do not edit.", f'#define QtVersion "{release}"']
    for package, prefix in PACKAGES:
        found = wheel(package, version(package) if package == "Pillow" else release)
        lines += [f'#define {prefix}Url "{found["url"]}"', f'#define {prefix}Sha "{found["digests"]["sha256"]}"']
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"pinned PySide6 {release}, Pillow {version('Pillow')}")


if __name__ == "__main__":
    main()
